services:
    bw-trading-pg:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: bw-trading-db
        ports:
            - "5433:5432"

volumes:
    postgres_data:
